//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiracleGun.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiracleGun.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;\u0421\u0424 033&quot;: {&quot;name&quot;: &quot;\u0421\u0424 033&quot;, &quot;f&quot;: 1.047, &quot;etta&quot;: 0.236, &quot;alpha_k&quot;: 1.039, &quot;T_1&quot;: 3000.0, &quot;ro&quot;: 1.6, &quot;I_k&quot;: 0.17, &quot;Z_k&quot;: 1.331, &quot;k_1&quot;: 0.309, &quot;lambda_1&quot;: 1.7, &quot;k_2&quot;: 0.743, &quot;lambda_2&quot;: -0.996, &quot;k_f&quot;: 0.0003, &quot;k_l&quot;: 0.0016}, &quot;\u0412\u0423 \u0444\u043b&quot;: {&quot;name&quot;: &quot;\u0412\u0423 \u0444\u043b&quot;, &quot;f&quot;: 1.005, &quot;etta&quot;: 0.234, &quot;alpha_k&quot;: 1.03, &quot;T_1&quot;: 2873.0, &quot;ro&quot;: 1.6, &quot;I_k&quot;: 0.15, &quot;Z_k&quot;: 0.113, &quot;k_1&quot;: 1.795, &quot;lambda_1&quot;: -0.417, &quot;k_2&quot;: 0.9, &quot;lambda_2&quot;: -2.487, &quot;k_f&quot;: 0.0003, &quot;k_l&quot;: 0.0016}, &quot;\u0412 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string gpowders {
            get {
                return ResourceManager.GetString("gpowders", resourceCulture);
            }
        }
    }
}
